site_name = 'Niquhiko'
footnote = 'My footnote'

[allowed_clean]
html_tags = ['h1', 'h2', 'h3', 'br', 'p', 'strong', 'em', 'blockquote', 'code', 'button', 'a', 'ol', 'ul', 'li', 'img', 'table', 'tr', 'td', 'tbody', 'pre']
characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!?$%*&~`():'\"/"
letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

allowed_file_extensions = ['txt', 'md', 'png', 'jpg', 'jpeg', 'gif']

[allowed_clean.html_attributes]
img = ['src']

[roles.guest]
permissions = ['CAN_LOGIN', 'CAN_REGISTER', 'CAN_LIKE']

[roles.user]
permissions = ['CAN_LOGOUT', 'CAN_LIKE']

[roles.admin]
permissions = ['CAN_LOGOUT', 'CAN_WRITE_POSTS', 'CAN_LIKE', 'CAN_UPLOAD_FILES']
