site_name = 'Niquhiko'
footnote = 'My footnote'

[allowed_clean]
html_tags = ['h1', 'h2', 'h3', 'br', 'p', 'strong', 'em', 'blockquote', 'code', 'button', 'a', 'ol', 'ul', 'li', 'img', 'table', 'tr', 'td', 'tbody', 'pre']
characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!?$%*&~`():'\"/"
letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

[roles.guest]
permissions = ['CAN_LOGIN', 'CAN_REGISTER']

[roles.user]
permissions = ['CAN_LOGOUT']

[roles.admin]
permissions = ['CAN_LOGOUT', 'CAN_WRITE_POSTS']
