site_name = 'Niquhiko'
footnote = '&#8593; This website was made possible with these tools! &#8593;'


# --------------------------------------- #
# Site Colors
# --------------------------------------- #
[site_colors]
background = 'rgb(27, 27, 27)'
background_accent = 'rgb(38, 38, 38)'

accent = 'rgb(255, 174, 0)'
accent_hover = 'rgb(255, 214, 92)'


# --------------------------------------- #
# Allowed Clean
# --------------------------------------- #
[allowed_clean]
html_tags = ['h1', 'h2', 'h3', 'br', 'p', 'strong', 'em', 'blockquote', 'code', 'button', 'a', 'ol', 'ul', 'li', 'img', 'table', 'tr', 'td', 'tbody', 'pre']
characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!?$%*&~`():'\"/"
letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

allowed_file_extensions = ['txt', 'md', 'png', 'jpg', 'jpeg', 'gif']

[allowed_clean.html_attributes]
img = ['src']
a = ['href']


# --------------------------------------- #
# Roles
# --------------------------------------- #
[roles.guest]
permissions = ['CAN_LOGIN', 'CAN_REGISTER', 'CAN_LIKE']

[roles.user]
permissions = ['CAN_LOGOUT', 'CAN_LIKE']

[roles.admin]
permissions = ['CAN_LOGOUT', 'CAN_WRITE_POSTS', 'CAN_LIKE', 'CAN_UPLOAD_FILES']


# --------------------------------------- #
# Link Badges
# --------------------------------------- #
[link_badges.niquhiko]
link = 'https://github.com/artelephantb/niquhiko'
image_source = '/static/badges/niquhiko.png'

[link_badges.simple_css]
link = 'https://simplecss.org'
image_source = '/static/badges/simple_css.png'

[link_badges.stack_edit]
link = 'https://stackedit.io'
image_source = '/static/badges/stack_edit.png'
